name: Publish Docker image
on:
  release:
    types: published
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.2
      - name: Set up JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 14-ea
          java-package: jdk
          architecture: x64
      - name: Build with Gradle
        run: gradle build
      - name: Push to GitHub Packages
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
          TAG: docker.pkg.github.com/sildvauresberg/demo/demo-app
        run: |
          echo $CR_PAT | docker login docker.pkg.github.com -u sildvauresberg --password-stdin
          docker build -t $TAG .
          docker push $TAG
